### ISSUE TITLE
Dispotable Tools with Disposable Airlines and Theme

### ISSUE THREAD

**Issue by CRolfe87** [FatihKoz/DisposableTools#7]
Modules all work fine except when I go to the Airlines page.
Running phpVMS 7.0.0-dev+210916.a0309b
and the latest releases for DisposableTech, JumpSeat, Disposableirlines, and DisposableTools.

These errors on the airlines page only occur when the DisposableTools is active, once I disable it and try the Airlines page it loads fine:

[2021-09-30 04:16:14] production.ERROR: Error running migration for DisposableTools; error=Symfony\Component\Console\Exception\CommandNotFoundException: The command "module:migrate DisposableTools" does not exist. in /volume1/web/PFLVA/vendor/laravel/framework/src/Illuminate/Console/Application.php:180

[2021-09-30 04:20:00] production.ERROR: Maximum execution time of 600 seconds exceeded {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 600 seconds exceeded at /volume1/web/PFLVA/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:521)

At first I was exceeding the memory limit so I increased it, then I exceed the 240 second limit, so I increased it.

**Comment by FatihKoz** [comment]
Hi,

First error (the one about migration) is something we were not able to fix yet and caused by the core phpvms v7. Re-visiting your.phpvms.site/admin or your.phpvms.site/update should let it pass that migration check. Happens when you first install the module via phpvms module manager or enable/disable modules from admin interface.

The second one however, looks like you are reaching the limits of the (Disposable Tools) Flights Map Widget and getting a timeout. Even though I tried making it use less resources and less time to build the data needed for the map, it still may not be able to handle much flights.

At Airline details page **map tries to load all the flights of your airline**, without any restrictions applied, like the flights map of an airline's in-flight magazine. You can limit it or disable it completely.

Kindly check;
`..\resources\views\layouts\Disposable_v2\modules\DisposableAirlines\airline.blade.php`

or (if you are not using Disposable Theme v2)
`..\modules\DisposableAirlines\Resources\Views\airline.blade.php`

in that blade you will see the widget being loaded with;
`@widget('Modules\DisposableTools\Widgets\FlightsMap', ['source' => $airline->id])`

applying a limit will be like this;
`@widget('Modules\DisposableTools\Widgets\FlightsMap', ['source' => $airline->id, 'limit' => 1000])`

or you can disable that widget being loaded at all with this;
`{{-- @widget('Modules\DisposableTools\Widgets\FlightsMap', ['source' => $airline->id]) --}}`

Hope this helps, if not please do not hesitate to contact.

**Comment by CRolfe87** [comment]
The issue indeed appears to be with my airlines ridiculously high flight count. L

Limiting the flight count in the map allowed it to load. I am however electing to just disable it for faster loading and because we are more of a ‘fly everywhere to everywhere’ kind of airline (charter type)

**Comment by FatihKoz** [comment]
Yeah, if this is the case you may consider disabling that map widget at all and use it only for displaying fleet locations maybe (if you are limiting aircraft usage of course).

My pleasure, glad you liked the addons ;) 

Safe flights
